Repository AY1920S1-CS2103-F09-2/main, pull requests merged in 2019-11, with the labels that each got.

#258 Centralize storage
  src/main/java/dream/fcard/MainApp.java
  src/main/java/dream/fcard/gui/controllers/jsjava/JavaEditorController.java
  src/main/java/dream/fcard/gui/controllers/windows/MainWindow.java
  src/main/java/dream/fcard/logic/stats/Session.java
  src/main/java/dream/fcard/logic/stats/SessionList.java
  src/main/java/dream/fcard/logic/stats/Stats.java
  src/main/java/dream/fcard/logic/storage/Schema.java
  src/main/java/dream/fcard/logic/storage/StatsStorageManager.java
  src/main/java/dream/fcard/logic/storage/StorageManager.java
  src/main/java/dream/fcard/util/DateTimeUtil.java
  src/main/java/dream/fcard/util/code/data/Main.class
  src/main/java/dream/fcard/util/code/data/Main.java
  src/main/java/dream/fcard/util/code/data/input.txt
  src/main/java/dream/fcard/util/code/data/test.js
  src/main/java/dream/fcard/util/json/JsonParser.java
  src/test/java/dream/fcard/util/code/JavascriptRunnerTest.java
  stats/stats.txt
Labels: severity.High, v1.4

#271 Update Documentation
  .gitignore
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/huiminlim.adoc
  src/main/java/dream/fcard/model/cards/FrontBackCard.java
  src/main/java/dream/fcard/model/cards/MultipleChoiceCard.java
  src/test/java/dream/fcard/model/cards/MultipleChoiceCardTest.java
Labels: v1.4

#272 Update PPP
  .gitignore
  docs/team/huiminlim.html
Labels: v1.4

#276 Update DG
  docs/DeveloperGuide.adoc
  docs/diagrams/ConfigurePriorityFlashCardTestSetSequenceDiagram.puml
  docs/diagrams/PriorityFlashCardTestSetSequenceDiagram.puml
  docs/images/ConfigurePriorityFlashCardTestSetSequenceDiagram.png
  docs/images/PriorityFlashCardTestSetSequenceDiagram.png
  docs/team/huiminlim.adoc
Labels: v1.4

#277 added cli and did checkstyle fix
  src/main/java/dream/fcard/core/Main.java
  src/main/java/dream/fcard/gui/controllers/windows/CliEditor.java
  src/main/resources/fonts/Inconsolata.otf
Labels: priority.High, v1.4

#278 Update DG
  docs/DeveloperGuide.adoc
  docs/diagrams/MultipleChoiceCard.puml
Labels: v1.4

#279 history and clear
  src/main/java/dream/fcard/gui/controllers/windows/CliEditor.java
Labels: type.Enhancement, v1.4

#281 Update DG
  docs/DeveloperGuide.adoc
  docs/diagrams/MultipleChoiceCard.puml
  docs/images/MultipleChoiceCardCreation.png
Labels: v1.4

#293 Edit card cli
  src/main/java/dream/fcard/logic/respond/Responses.java
  src/main/java/dream/fcard/model/cards/FlashCard.java
Labels: v1.4

#294 Debug create deck regex
  src/main/java/dream/fcard/logic/respond/Responses.java
Labels: v1.4

#295 Added cli delete cards
  .travis.yml
  src/main/java/dream/fcard/logic/respond/Responses.java
  src/main/java/dream/fcard/model/Deck.java
Labels: v1.4

#315 Added: delete deck CLI
  .gitignore
  src/main/java/dream/fcard/logic/respond/Responses.java
  src/main/java/dream/fcard/model/cards/FrontBackCard.java
  src/main/java/dream/fcard/model/cards/JavascriptCard.java
Labels: v1.4

#316 Debug: add and remove card from high and low pri queue
  src/main/java/dream/fcard/model/Deck.java
  src/main/java/dream/fcard/model/cards/FlashCard.java
  src/main/java/dream/fcard/model/cards/FrontBackCard.java
  src/main/java/dream/fcard/model/cards/JavaCard.java
  src/main/java/dream/fcard/model/cards/JavascriptCard.java
Labels: v1.4

#318 Debug test when high pri cards <= 6
  src/main/java/dream/fcard/model/Deck.java
Labels: v1.4

#330 Updated Ui image, docs
  docs/images/Ui.png
  docs/images/Ui_old.png
  docs/team/huiminlim.adoc
  docs/tutorials/TracingCode.adoc
Labels: v1.4

#333 Debug help command overflow
  docs/UserGuide.adoc
  src/main/java/dream/fcard/logic/respond/commands/HelpCommand.java
Labels: v1.4

#334 Debug: Create card window gets cut off
  .travis.yml
  docs/UserGuide.adoc
  docs/team/huiminlim.adoc
  src/main/java/dream/fcard/gui/controllers/displays/createandeditdeck/EditDeckDisplay.java
  src/main/java/dream/fcard/gui/controllers/windows/MainWindow.java
  src/main/resources/view/Windows/CardCreatingWindow.fxml
Labels: v1.4

#335 Updated UG: GUI supports display well at max 10 cards
  docs/UserGuide.adoc
Labels: v1.4

#336 Newcli
  src/main/java/dream/fcard/gui/controllers/windows/CliEditor.java
  src/main/java/dream/fcard/gui/controllers/windows/MainWindow.java
  src/main/resources/view/Windows/MainWindow.fxml
Labels: priority.High

#339 docs
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/ahaliq.adoc
Labels: v1.4

#344 Update Docs
  .travis.yml
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/huiminlim.adoc
Labels: v1.4

#345 Update docs
  docs/UserGuide.adoc
  src/main/java/dream/fcard/model/Deck.java
  src/main/java/dream/fcard/model/cards/FlashCard.java
  src/main/java/dream/fcard/model/cards/FrontBackCard.java
  src/main/java/dream/fcard/model/cards/MultipleChoiceCard.java
Labels: v1.4

#348 Update PPP
  docs/team/huiminlim.adoc
Labels: v1.4

#352 Update PPP
  docs/DeveloperGuide.adoc
  docs/team/huiminlim.adoc
Labels: v1.4

#353 Update DG
  docs/DeveloperGuide.adoc
Labels: v1.4

#355 Debug CLI view command
  docs/UserGuide.adoc
  src/main/java/dream/fcard/logic/respond/Responses.java
  src/main/java/dream/fcard/model/State.java
Labels: v1.4

#357 Update PPP
  docs/team/huiminlim.adoc
Labels: v1.4

#358 Debug Help command
  docs/team/huiminlim.adoc
  src/main/java/dream/fcard/logic/respond/commands/HelpCommand.java
Labels: v1.4

#364 Debug delete command cli
  .travis.yml
  src/main/java/dream/fcard/logic/respond/Responses.java
Labels: v1.4

#373 Updated Docs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: v1.4
