Repository AY1920S1-CS2103-F09-2/main, pull requests merged in 2019-10, with the labels that each got.

#86 Added: documentation for flashcard
  docs/DeveloperGuide.adoc
  docs/images/cards_class_diagram.png
  src/main/java/dream/fcard/model/Deck.java
  src/main/java/dream/fcard/model/State.java
  src/main/java/dream/fcard/model/cards/MultipleChoiceCard.java
Labels: v1.3

#87 Added: Multiple Choice randomizer and Checks for no duplicated choices
  src/main/java/dream/fcard/logic/exam/Exam.java
  src/main/java/dream/fcard/logic/exam/ExamRunner.java
  src/main/java/dream/fcard/model/Deck.java
  src/main/java/dream/fcard/model/State.java
  src/main/java/dream/fcard/model/cards/FlashCard.java
  src/main/java/dream/fcard/model/cards/FrontBackCard.java
  src/main/java/dream/fcard/model/cards/MultipleChoiceCard.java
  src/main/java/dream/fcard/model/exceptions/DeckNotFoundException.java
  src/main/java/dream/fcard/model/exceptions/DuplicateInChoicesException.java
  src/main/java/dream/fcard/model/exceptions/IndexNotFoundException.java
  src/test/java/dream/fcard/model/cards/FrontBackCardTest.java
  src/test/java/dream/fcard/model/cards/MultipleChoiceCardTest.java
Labels: v1.3

#94 Revert "GUI initial implementation"
  .\src\test\java\dream\fcard\util\data\Test.java
  docs/mockups/FlashCard Pro 2019-10-17.pdf
  src/main/java/dream/fcard/MainApp.java
  src/main/java/dream/fcard/gui/MainWindow.java
  src/main/java/dream/fcard/gui/MainWindowOld.java
  src/main/java/dream/fcard/gui/Ui.java
  src/main/java/dream/fcard/gui/UiManager.java
Labels: type.Bug, v1.3

#96 Delete .\src\test\java\dream\fcard\util\data\Test.java
  .\src\test\java\dream\fcard\util\data\Test.java
Labels: type.Bug

#100 Added: MCQ randomizer
  src/main/java/dream/fcard/core/commons/core/LogsCenter.java
  src/main/java/dream/fcard/logic/storage/StorageManager.java
  src/main/java/dream/fcard/model/cards/MultipleChoiceCard.java
  src/test/java/dream/fcard/logic/storage/StorageManagerTest.java
  src/test/java/dream/fcard/util/FileReadWriteTest.java
Labels: v1.3

#101 Edit: MCQ refactor method
  src/main/java/dream/fcard/model/cards/MultipleChoiceCard.java
  src/main/java/dream/fcard/model/exceptions/DeckNotFoundException.java
  src/main/java/dream/fcard/model/exceptions/DuplicateInChoicesException.java
  src/main/java/dream/fcard/model/exceptions/IndexNotFoundException.java
  src/test/java/dream/fcard/model/StateTest.java
  src/test/java/dream/fcard/model/cards/FrontBackCardTest.java
  src/test/java/dream/fcard/model/cards/MultipleChoiceCardTest.java
Labels: v1.3

#102 Added: Priority implementation for cards and deck
  src/main/java/dream/fcard/model/Deck.java
  src/main/java/dream/fcard/model/cards/FlashCard.java
  src/main/java/dream/fcard/model/cards/FrontBackCard.java
  src/main/java/dream/fcard/model/cards/JavascriptCard.java
  src/main/java/dream/fcard/model/cards/MultipleChoiceCard.java
  src/main/java/dream/fcard/model/cards/Priority.java
  src/test/java/dream/fcard/model/cards/MultipleChoiceCardTest.java
  src/test/java/dream/fcard/util/FileReadWriteTest.java
Labels: v1.3

#103 Add: reposense
  _reposense/config.json
Labels: v1.3

#104 Added: create subset of deck with cards of differing priorities for examrunner
  src/main/java/dream/fcard/model/Deck.java
Labels: v1.3

#106 Update DeveloperGuide.adoc
  docs/DeveloperGuide.adoc
Labels: v1.3

#108 Added: documentation for flashcards
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/flashcards_priority cards.png
Labels: v1.3

#115 Storage responses
  src/main/java/dream/fcard/logic/respond/Responses.java
  src/main/java/dream/fcard/logic/storage/StorageManager.java
  src/main/java/dream/fcard/model/State.java
  src/main/java/dream/fcard/util/FileReadWrite.java
  src/test/java/dream/fcard/logic/respond/ResponsesTest.java
Labels: priority.High

#118 Updated: Documentation
  docs/DeveloperGuide.adoc
Labels: v1.3

#121 Edit: windows filepath
  src/main/java/dream/fcard/logic/respond/Responder.java
  src/main/java/dream/fcard/logic/storage/StorageManager.java
Labels: v1.3

#122 v1.3
  _reposense/config.json
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/CodeClassDiagram.puml
  docs/diagrams/JSCardActivityDiagram.puml
  docs/images/CodeClassDiagram.png
  docs/images/ExamRunnerActivityDiagram.png
  docs/images/JSCardActivityDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/cards_class_diagram.png
  docs/images/flashcards_priority cards.png
  docs/images/jsonParserProcessDynamicValue.png
  src/main/java/dream/fcard/core/commons/core/LogsCenter.java
  src/main/java/dream/fcard/logic/exam/Exam.java
  src/main/java/dream/fcard/logic/exam/ExamRunner.java
  src/main/java/dream/fcard/logic/exam/Result.java
  src/main/java/dream/fcard/logic/respond/Responder.java
  src/main/java/dream/fcard/logic/respond/Responses.java
  src/main/java/dream/fcard/logic/storage/StorageManager.java
  src/main/java/dream/fcard/model/Deck.java
  src/main/java/dream/fcard/model/State.java
  src/main/java/dream/fcard/model/cards/FlashCard.java
  src/main/java/dream/fcard/model/cards/FrontBackCard.java
  src/main/java/dream/fcard/model/cards/JavascriptCard.java
  src/main/java/dream/fcard/model/cards/MultipleChoiceCard.java
  src/main/java/dream/fcard/model/cards/Priority.java
  src/main/java/dream/fcard/model/exceptions/DeckNotFoundException.java
  src/main/java/dream/fcard/model/exceptions/DuplicateInChoicesException.java
  src/main/java/dream/fcard/model/exceptions/IndexNotFoundException.java
  src/main/java/dream/fcard/util/FileReadWrite.java
  src/test/java/dream/fcard/logic/respond/ResponsesTest.java
  src/test/java/dream/fcard/logic/storage/StorageManagerTest.java
  src/test/java/dream/fcard/model/StateTest.java
  src/test/java/dream/fcard/model/cards/FrontBackCardTest.java
  src/test/java/dream/fcard/model/cards/MultipleChoiceCardTest.java
  src/test/java/dream/fcard/util/FileReadWriteTest.java
  src/test/java/dream/fcard/util/code/JavaRunnerTest.java
Labels: v1.3

#123 Edit: Indexing for cards and deck
  src/main/java/dream/fcard/model/Deck.java
  src/main/java/dream/fcard/model/State.java
  src/main/java/dream/fcard/model/cards/MultipleChoiceCard.java
Labels: v1.3

#124 Add: documentation for flashcards
  src/main/java/dream/fcard/model/cards/FlashCard.java
  src/main/java/dream/fcard/model/cards/FrontBackCard.java
  src/main/java/dream/fcard/model/cards/MultipleChoiceCard.java
Labels: v1.3

#135 Delete config.json
  _reposense/config.json
Labels: v1.3

#139 Add: hasChoice method for flashcards
  src/main/java/dream/fcard/model/cards/FlashCard.java
  src/main/java/dream/fcard/model/cards/FrontBackCard.java
  src/main/java/dream/fcard/model/cards/JavascriptCard.java
  src/main/java/dream/fcard/model/cards/MultipleChoiceCard.java
Labels: v1.3

#140 Edit: javadoc for flashcard, state, deck
  src/main/java/dream/fcard/logic/storage/StorageManager.java
  src/main/java/dream/fcard/model/Deck.java
  src/main/java/dream/fcard/model/State.java
  src/main/java/dream/fcard/model/cards/FlashCard.java
  src/main/java/dream/fcard/model/cards/MultipleChoiceCard.java
  src/test/java/dream/fcard/logic/storage/StorageManagerTest.java
Labels: v1.3

#141 Add: UNKNOWN enum to Response
  src/main/java/dream/fcard/MainApp.java
  src/main/java/dream/fcard/logic/respond/Responses.java
Labels: v1.3

#144 Add: create empty deck and cards to deck in Responses
  src/main/java/dream/fcard/logic/respond/Responder.java
  src/main/java/dream/fcard/logic/respond/ResponseFunc.java
  src/main/java/dream/fcard/logic/respond/Responses.java
  src/main/java/dream/fcard/logic/respond/exception/DuplicateFoundException.java
  src/test/java/dream/fcard/logic/respond/ResponsesTest.java
Labels: v1.3

#145 Edit: Change shortcut of EXPORT command to (ex) from (e)
  src/main/java/dream/fcard/logic/respond/Responses.java
Labels: v1.3

#148 Edit: expand create to take in sentences input.
  src/main/java/dream/fcard/logic/respond/Responder.java
  src/main/java/dream/fcard/logic/respond/Responses.java
  src/main/java/dream/fcard/logic/respond/commands/Command.java
  src/main/java/dream/fcard/logic/respond/commands/CreateCommand.java
  src/main/java/dream/fcard/model/State.java
  src/main/java/dream/fcard/model/StateEnum.java
Labels: v1.3

#149 Edit: changed regex of edit to take in more specific input
  src/main/java/dream/fcard/logic/respond/Responses.java
Labels: v1.3

#150 Edit: implemented edit parsing
  docs/UserGuide.adoc
  src/main/java/dream/fcard/logic/respond/Responses.java
Labels: v1.3

#151 Split edit command into edit and remove
  src/main/java/dream/fcard/logic/respond/Responses.java
Labels: v1.3

#152 Debug: edit functionality
  src/main/java/dream/fcard/logic/respond/Responses.java
  src/main/java/dream/fcard/model/Deck.java
Labels: v1.3

#153 Added: logging
  src/main/java/dream/fcard/logic/respond/Responses.java
Labels: v1.3

#154 Add: create mcq in response
  docs/UserGuide.adoc
  src/main/java/dream/fcard/logic/respond/Responses.java
Labels: v1.3

#159 Add: call gui methods in responses for create deck
  src/main/java/dream/fcard/gui/components/FlashCardCell.java
  src/main/java/dream/fcard/logic/respond/Responses.java
Labels: v1.3

#160 Remove: flashcard evaluate exception
  src/main/java/dream/fcard/logic/exam/ExamRunner.java
  src/main/java/dream/fcard/logic/respond/commands/EditCommand.java
  src/main/java/dream/fcard/model/cards/FlashCard.java
  src/main/java/dream/fcard/model/cards/FrontBackCard.java
  src/main/java/dream/fcard/model/cards/JavaCard.java
  src/main/java/dream/fcard/model/cards/MultipleChoiceCard.java
Labels: v1.3

#161 Debug: edit functionality
  src/main/java/dream/fcard/logic/respond/Responder.java
  src/main/java/dream/fcard/logic/respond/ResponseFunc.java
  src/main/java/dream/fcard/logic/respond/Responses.java
  src/main/java/dream/fcard/logic/respond/commands/CreateCommand.java
  src/main/java/dream/fcard/logic/respond/commands/EditCommand.java
  src/main/java/dream/fcard/model/Deck.java
Labels: v1.3

#162 Add: create MCQ card functionality
  src/main/java/dream/fcard/logic/respond/Responses.java
  src/main/java/dream/fcard/logic/respond/commands/CreateCommand.java
Labels: v1.3

#166 Debug view function
  src/main/java/dream/fcard/logic/respond/Responses.java
Labels: v1.3
